import type { User } from "./types"

export const zennUsers: string[] = [
    'to3izo',
    'niiharamegumu',
    'kawarimidoll',
    'kima000',
    'anri99103',
    'sajikix',
    'euxn23',
    'chips0711',
    'otakakot',
    'strozw',
    'dai_shi',
    'inuinu',
    'moko-poi',
    'codemagic',
    'tsubasa_tech',
    'qaynam',
    'yueda256',
    'taichifukumoto',
    'uu',
    'yoshiyuki_sato',
]

export const qiitaUsers: string[] = [
    'yamazombie',
    'newta',
    'zunbero_zunbero',
    'akiraarika932',
    'araidon',
    'votepurchase',
    '_mi',
    'aokikenichi',
    'renesisu727',
    'TabataRin',
    'nqdior',
    'ahya_emon',
    'yonecoko',
    'ochx',
    'Sicut_study',
    'FukuharaYohei',
    'ko1nksm',
    'b-mente',
    'yamadagenki',
    'nucomiya'
]
  
export const users: User[] = [
  {
    userName: 'Alice',
    imgSrc: 'https://randomuser.me/api/portraits/women/1.jpg',
    introduction: 'Alice is a front-end developer with a passion for React and Vue.',
    zennId: zennUsers[0],
    qiitaId: qiitaUsers[0],
  },
  {
    userName: 'Bob',
    imgSrc: 'https://randomuser.me/api/portraits/men/1.jpg',
    introduction: 'Bob is a full-stack engineer specializing in Node.js and Express.',
    zennId: zennUsers[1],
    qiitaId: qiitaUsers[1],
  },
  {
    userName: 'Charlie',
    imgSrc: 'https://randomuser.me/api/portraits/men/2.jpg',
    introduction: 'Charlie loves working with databases and back-end services.',
    zennId: zennUsers[2],
    qiitaId: qiitaUsers[2],
  },
  {
    userName: 'Dave',
    imgSrc: 'https://randomuser.me/api/portraits/men/3.jpg',
    introduction: 'Dave is a cloud computing enthusiast and an AWS Certified Developer.',
    zennId: zennUsers[3],
    qiitaId: qiitaUsers[3],
  },
  {
    userName: 'Eve',
    imgSrc: 'https://randomuser.me/api/portraits/women/2.jpg',
    introduction: 'Eve is a data scientist passionate about machine learning and AI.',
    zennId: zennUsers[4],
    qiitaId: qiitaUsers[4],
  },
  {
    userName: 'Frank',
    imgSrc: 'https://randomuser.me/api/portraits/men/4.jpg',
    introduction: 'Frank is a DevOps expert specializing in CI/CD and infrastructure automation.',
    zennId: zennUsers[5],
    qiitaId: qiitaUsers[5],
  },
  {
    userName: 'Grace',
    imgSrc: 'https://randomuser.me/api/portraits/women/3.jpg',
    introduction: 'Grace is an iOS developer with a keen eye for UI/UX design.',
    zennId: zennUsers[6],
    qiitaId: qiitaUsers[6],
  },
  {
    userName: 'Hank',
    imgSrc: 'https://randomuser.me/api/portraits/men/5.jpg',
    introduction: 'Hank is a cybersecurity specialist with experience in network security.',
    zennId: zennUsers[7],
    qiitaId: qiitaUsers[7],
  },
  {
    userName: 'Ivy',
    imgSrc: 'https://randomuser.me/api/portraits/women/4.jpg',
    introduction: 'Ivy is a blockchain developer working on decentralized applications.',
    zennId: zennUsers[8],
    qiitaId: qiitaUsers[8],
  },
  {
    userName: 'Jack',
    imgSrc: 'https://randomuser.me/api/portraits/men/6.jpg',
    introduction: 'Jack is a game developer with expertise in Unity and C#.',
    zennId: zennUsers[9],
    qiitaId: qiitaUsers[9],
  },
  {
    userName: 'Kim',
    imgSrc: 'https://randomuser.me/api/portraits/women/5.jpg',
    introduction: 'Kim is a UI/UX designer who enjoys creating user-friendly interfaces.',
    zennId: zennUsers[10],
    qiitaId: qiitaUsers[10],
  },
  {
    userName: 'Leo',
    imgSrc: 'https://randomuser.me/api/portraits/men/7.jpg',
    introduction: 'Leo is an AI researcher focusing on deep learning and NLP.',
    zennId: zennUsers[11],
    qiitaId: qiitaUsers[11],
  },
  {
    userName: 'Mia',
    imgSrc: 'https://randomuser.me/api/portraits/women/6.jpg',
    introduction: 'Mia is a back-end engineer who loves working with microservices.',
    zennId: zennUsers[12],
    qiitaId: qiitaUsers[12],
  },
  {
    userName: 'Nina',
    imgSrc: 'https://randomuser.me/api/portraits/women/7.jpg',
    introduction: 'Nina is a mobile developer with experience in cross-platform development.',
    zennId: zennUsers[13],
    qiitaId: qiitaUsers[13],
  },
  {
    userName: 'Oscar',
    imgSrc: 'https://randomuser.me/api/portraits/men/8.jpg',
    introduction: 'Oscar is a Site Reliability Engineer with a background in monitoring and observability.',
    zennId: zennUsers[14],
    qiitaId: qiitaUsers[14],
  },
  {
    userName: 'Paul',
    imgSrc: 'https://randomuser.me/api/portraits/men/9.jpg',
    introduction: 'Paul is a data engineer building large-scale data pipelines.',
    zennId: zennUsers[15],
    qiitaId: qiitaUsers[15],
  },
  {
    userName: 'Quinn',
    imgSrc: 'https://randomuser.me/api/portraits/women/8.jpg',
    introduction: 'Quinn is an IoT specialist creating smart devices with Raspberry Pi.',
    zennId: zennUsers[16],
    qiitaId: qiitaUsers[16],
  },
  {
    userName: 'Rachel',
    imgSrc: 'https://randomuser.me/api/portraits/women/9.jpg',
    introduction: 'Rachel is an AI engineer developing models for natural language processing.',
    zennId: zennUsers[17],
    qiitaId: qiitaUsers[17],
  },
  {
    userName: 'Sam',
    imgSrc: 'https://randomuser.me/api/portraits/men/10.jpg',
    introduction: 'Sam is a Python developer who loves working with Flask and Django.',
    zennId: zennUsers[18],
    qiitaId: qiitaUsers[18],
  },
  {
    userName: 'Tina',
    imgSrc: 'https://randomuser.me/api/portraits/women/10.jpg',
    introduction: 'Tina is a Java developer working on enterprise-level applications.',
    zennId: zennUsers[19],
    qiitaId: qiitaUsers[19],
  }
];

export default users;
